FROM ruby:2.6.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs libgmp3-dev
RUN gem install bundler
RUN mkdir /app
WORKDIR /app
ENV BUNDLE_PATH /usr/local/bundle/
EXPOSE 3000
